export const products = [
  {
    id: 10,
    productName: "Women's Gentle-Support High-Waisted 7/8 Leggings",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_2.1.png", "/products/p_2.2.png"],
    salePrice: 80,
    regularPrice: 100,
  },
  {
    id: 11,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_2.2.png", "/products/p_2.2.png"],
    salePrice: 443,
    regularPrice: 555,
  },
  {
    id: 12,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_2.3.png", "/products/p_2.2.png"],
    salePrice: 80,
    regularPrice: 100,
  },
  {
    id: 13,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_2.4.png", "/products/p_2.2.png"],
    salePrice: 80,
    regularPrice: 100,
  },
  {
    id: 14,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_2.5.png"],
    salePrice: 80,
    regularPrice: 100,
  },
  {
    id: 15,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_3.1.png", "/products/p_2.2.png"],
    salePrice: 80,
    regularPrice: 100,
  },
  {
    id: 16,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_3.2.png", "/products/p_2.2.png"],
    salePrice: 80,
    regularPrice: 100,
  },
  {
    id: 17,
    productName: "Nike Sportswear Club Fleece",
    productTitle: "Men's Monogram Hoodie",
    images: ["/products/p_3.3.png", "/products/p_2.2.png"],
    salePrice: 80,
    regularPrice: 100,
  },
];

// productImage: [
//       {
//         productColor: "red",
//         images: ["/products/p_2.1.png", "/products/p_2.2.png"],
//         size: ["s", "m", "l"],
//       },
//       {
//         productColor: "blue",
//         images: ["/products/p_2.3.png", "/products/p_2.4.png"],
//         productSizes: ["s", "m", "xl", "xxl"],
//       },
//     ],

// img: [
//   { "/products/p_2.1.png": ["/products/p_2.1.png"] },
//   { "/products/p_2.1.png": ["/products/p_2.1.png"] },
//   { "/products/p_2.1.png": ["/products/p_2.1.png"] },
// ],
