export const products = [
  {
    id: 10,
    name: "Women's Gentle-Support High-Waisted 7/8 Leggings",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_2.1.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 11,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_2.2.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 12,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_2.3.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 13,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_2.4.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 10,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_2.5.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 11,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_3.1.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 12,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_3.2.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
  {
    id: 13,
    name: "Nike Sportswear Club Fleece",
    title: "Men's Monogram Hoodie",
    img: ["/products/p_3.3.png", "/products/p_2.2.png"],
    newPrice: 80,
    oldPrice: 100,
  },
];

// img: [
//   { "/products/p_2.1.png": ["/products/p_2.1.png"] },
//   { "/products/p_2.1.png": ["/products/p_2.1.png"] },
//   { "/products/p_2.1.png": ["/products/p_2.1.png"] },
// ],
